# Optimized pre-commit configuration for scientific bioinformatics tools
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # Allow larger files for scientific data
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: check-json
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]  # Slightly longer for scientific code

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [
          --max-line-length=100,
          --extend-ignore=E203,W503,E501,  # More lenient for scientific code
          --max-complexity=15,  # Higher complexity allowed
          --select=E,W,F,  # Only check errors, warnings, and pyflakes
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [
          --ignore-missing-imports,
          --no-strict-optional,  # More lenient for scientific libraries
          --warn-return-any,  # Warn but don't fail
        ]

  # Scientific-specific checks
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]
