name: CI Ultra-Streamlined

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  tags:
    - 'v*'

jobs:
  # Pre-commit validation (replaces quality checks)
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure

  # Tests (runs in parallel with pre-commit)
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    strategy:
      matrix:
        python-version: ['3.9', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install -e .

    - name: Run tests
      run: |
        pytest test_pysee.py
        pytest tests/ --maxfail=3

    - name: Test example script
      run: python example.py

  # Build (runs after pre-commit passes)
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: pre-commit
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build and check package
      run: |
        python -m build
        twine check dist/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.sha }}
        path: dist/
        retention-days: 7

  # Security scan (main branch only, non-blocking)
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install bandit safety

    - name: Security scan
      run: |
        bandit -r pysee/ -f json -o bandit-report.json || true
        safety check --json --output safety-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  # Release (only on tags)
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [pre-commit, test, build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          dist/*
        draft: false
        prerelease: false
        allowUpdates: true

  # Summary
  summary:
    runs-on: ubuntu-latest
    needs: [pre-commit, test, build, security]
    if: always()

    steps:
    - name: CI Summary
      run: |
        echo "::group::CI Summary"
        echo "Pre-commit: ${{ needs.pre-commit.result }}"
        echo "Tests: ${{ needs.test.result }}"
        echo "Build: ${{ needs.build.result }}"
        echo "Security: ${{ needs.security.result }}"
        echo "::endgroup::"
